#!/bin/bash
set -o errexit -o nounset -o pipefail
command -v shellcheck >/dev/null && shellcheck "$0"

rm -rf protos/ibc-go
mkdir -p protos/ibc-go
echo "Autogenerated folder, see export_protos.sh" > protos/ibc-go/README.md

buf export protos/ibc-go-src/ --output protos/ibc-go
